version: '3.3'
services:
  api:
    build: ./restapi
    container_name: 'restfavads_api'
    ports:
      - 3000:3000
    volumes:
      - ./restapi:/go/src/restapi
    links:
      - database

  database:
    image: mongo:3.0
    container_name: 'restfavads_mongo'
    command: mongod --smallfiles --quiet --logpath=/dev/null